#if !(defined(GO) && defined(GOM) && defined(GO2) && defined(DATA))
#error meh!
#endif

GO(GetVolumeInformationA,uSppuuuupu)
GO(GetDriveTypeA,uSp)
GO(IsBadWritePtr,uSpu)
GO(IsBadReadPtr,uSpu)
GO(IsBadStringPtrW,uSpu)
GO(IsBadStringPtrA,uSpu)
GO(DisableThreadLibraryCalls,uSi)
GO(CreateThread,iSpuppuu)
GO(ResumeThread,uSi)
GO(CreateEventA,iSpuup)
GO(CreateEventW,iSpuup)
GO(SetEvent,uSi)
GO(ResetEvent,uSi)
GO(WaitForSingleObject,uSiu)
GO(WaitForMultipleObjects,uSuiuu)
GO(ExitThread,vSu)
GO(GetSystemInfo,vSp)
GO(GetVersion,iSv)
GO(HeapCreate,iSuuu)
GO(HeapAlloc,pSiuu)
GO(HeapDestroy,uSi)
GO(HeapFree,uSiup)
GO(HeapSize,uSiup)
GO(HeapReAlloc,pSiupu)
GO(HeapValidate,uSiup)
GO(GetProcessHeap,iSv)
GO(VirtualAlloc,pSpuuu)
GO(VirtualFree,uSpuu)
GO(InitializeCriticalSection,vSp)
GO(InitializeCriticalSectionAndSpinCount, vSpu)
GO(EnterCriticalSection,vSp)
GO(LeaveCriticalSection,vSp)
GO(DeleteCriticalSection,vSp)
GO(TlsAlloc,uSv)
GO(TlsFree,uSu)
GO(TlsGetValue,pSu)
GO(TlsSetValue,uSup)
GO(GetCurrentThreadId,uSv)
GO(GetCurrentProcess,iSv)
GO(LocalAlloc,iSuu)
GO(LocalReAlloc,iSiuu)
GO(LocalLock,pSi)
GO(GlobalAlloc,iSuu)
GO(GlobalReAlloc,iSiuu)
GO(GlobalLock,pSi)
GO(GlobalSize,uSi)
GO(MultiByteToWideChar,iSuupipi)
GO(WideCharToMultiByte,iSuupipipu)
GO(GetVersionExA,uSp)
GO(GetVersionExW,uSp)
GO(CreateSemaphoreA,iSpiip)
GO(CreateSemaphoreW,iSpiip)
GO(QueryPerformanceCounter,uSp)
GO(QueryPerformanceFrequency, uSp)
GO(LocalHandle,iSp)
GO(LocalUnlock,uSi)
GO(LocalFree,iSi)
GO(GlobalHandle,iSp)
GO(GlobalUnlock,uSi)
GO(GlobalFree,iSi)
GO(LoadResource,iSii)
GO(ReleaseSemaphore,uSiip)
GO(CreateMutexA,iSpup)
GO(CreateMutexW,iSpup)
GO(ReleaseMutex,uSi)
GO(SignalObjectAndWait, vFv)
GO(FindResourceA,iSipp)
GO(LockResource,pSi)
GO(FreeResource, vFv)
GO(SizeofResource,uSii)
GO(CloseHandle,uSi)
GO(GetCommandLineA,pSv)
GO(GetEnvironmentStringsW,pSv)
GO(FreeEnvironmentStringsW,uSp)
GO(FreeEnvironmentStringsA,uSp)
GO(GetEnvironmentStrings, pSp)
GO(GetStartupInfoA,vSp)
GO(GetStdHandle,iSu)
GO(GetFileType,uSi)
GO(GetFileAttributesA,uSp)
GO(SetHandleCount,uSu)
GO(GetACP,uSv)
GO(GetModuleFileNameA,uSipu)
GO(SetUnhandledExceptionFilter, pSp)
GO(LoadLibraryA,iSp)
GO(GetProcAddress,pSip)
GO(FreeLibrary,uSi)
GO(CreateFileMappingA,iSipuuup)
GO(OpenFileMappingA,iSuup)
GO(MapViewOfFile,pSiuuuu)
GO(UnmapViewOfFile,uSp)
GO(Sleep,vSu)
GO(GetModuleHandleA,iSp)
GO(GetModuleHandleW,iSp)
GO(GetProfileIntA,uSppi)
GO(GetPrivateProfileIntA,uSppip)
GO(GetPrivateProfileStringA,iSppppup)
GO(WritePrivateProfileStringA,uSpppp)
GO(GetLastError,uSv)
GO(SetLastError,vSu)
GO(InterlockedIncrement,iSp)
GO(InterlockedDecrement,iSp)
GO(GetTimeZoneInformation, pSp)
GO(OutputDebugStringA,vSp)
GO(GetLocalTime,vSp)
GO(GetSystemTime,vSp)
GO(GetSystemTimeAsFileTime,vSp)
GO(GetEnvironmentVariableA,uSppu)
GO(SetEnvironmentVariableA,uSpp)
GO(RtlZeroMemory, pSp)
GO(RtlMoveMemory, pSp)
GO(RtlFillMemory, pSp)
GO(GetTempPathA,uSup)
GO(FindFirstFileA,iSpp)
GO(FindNextFileA,uSip)
GO(FindClose,uSi)
GO(FileTimeToLocalFileTime,uSpp)
GO(DeleteFileA,uSp)
GO(ReadFile,uSipuup)
GO(WriteFile,uSipuup)
GO(SetFilePointer,uSiipu)
GO(GetTempFileNameA,uSppup)
GO(CreateFileA,iSpuupuui)
GO(GetSystemDirectoryA,uSpu)
GO(GetWindowsDirectoryA,uSpu)
GO(GetCurrentDirectoryA,uSup)
GO(SetCurrentDirectoryA,uSp)
GO(CreateDirectoryA,uSpp)
GO(GetShortPathNameA,uSppu)
GO(GetFullPathNameA,uSpupp)
GO(SetErrorMode,uSu)
GO(IsProcessorFeaturePresent,uSu)
GO(IsDebuggerPresent,uSv)
GO(InterlockedExchange,iSpi)
GO(InterlockedCompareExchange,pSppp)
GO(MulDiv, pSp)
GO(lstrcmpiA,iSpp)
GO(lstrlenA,iSp)
GO(lstrlenW,iSp)
GO(lstrcpyA,pSpp)
GO(lstrcpynA,pSppi)
GO(GetProcessVersion,uSu)
GO(GetCurrentThread,iSv)
GO(GetOEMCP,uSv)
GO(GetCPInfo, pSp)
GO(DuplicateHandle,uSiiiiuuu)
GO(GetTickCount, pSv)
GO(SetThreadAffinityMask,uSiu)
GO(GetCurrentProcessId,pSv)
GO(GlobalMemoryStatus,vSp)
GO(GetThreadPriority,iSi)
GO(SetThreadPriority,uSii)
GO(TerminateProcess,uSiu)
GO(ExitProcess,vSu)
GO(SetThreadIdealProcessor, pSp)
GO(SetProcessAffinityMask, pSp)
GO(EncodePointer, pSp)
GO(DecodePointer, pSp)
GO(GetThreadLocale,uSv)
GO(GetLocaleInfoA,iSuupi)
GO(malloc,pFi)
GO(_initterm,iFpv)
GO(__dllonexit,pFv)
GO(_snprintf,iFv)
GO(free,vFp)
GO(_errno,iFv)
GO(strrchr,pFpv)
GO(strchr,pFpv)
GO(strlen,iFp)
GO(strcpy,pFpv)
GO(strncpy,pFpv)
GO(wcscpy,pFpv)
GO(strcmp,iFpv)
GO(strncmp,iFpvi)
GO(strcat,pFpv)
GO(_stricmp,iFpv)
GO(_strnicmp,iFpv)
GO(_strdup,pFp)
GO(_setjmp3,iFpv)
GO(isalnum,iFi)
GO(isspace,iFi)
GO(isalpha,iFi)
GO(isdigit,iFi)
GO(memmove,pFpv)
GO(memcmp,iFpv)
GO(memset,pFpv)
GO(memcpy,pFpv)
GO(time,uFp)
GO(rand,iFv)
GO(srand,vFi)
GO(log10,vFv)
GO(pow,dFdv)
GO(cos,vFv)
GO(fabs,dFd)
GO(sqrt,dFd)
GO(sin,dFd)
GO(atan2,dFdv)
GO(acos,dFd)
GO(toupper,cFc)
GO(tolower,cFc)
GO(atoi,iFc)
GO(atof,dFc)
GO(tan,dFd)
GO(exp, dFd)
GO(atan,dFd)
GO(fmod,dFdv)
GO(_ftol,IFv)
GO(_CIpow,dFv)
GO(_CIcos,dFv)
GO(_CIsin,dFv)
GO(_CIsqrt,dFv)
GO(_CImod,dFv)
GO(_CIfmod,dFv)
GO(ldexp, dFdi)
GO(frexp, dFdp)
GO(sprintf,iFpv)
GO(sscanf,iFpv)
GO(fopen,pFpv)
GO(fclose,iFv)
GO(fwrite,iFv)
GO(_mkdir,iFp)
GO(fprintf,iFpv)
GO(printf,iFpv)
GO(getenv,pFp)
GO(floor,dFd)
GO(_EH_prolog,vFv)
GO(calloc,vFi)
GO(realloc,vFv),
GO(GetDriverModuleHandle,iSi)
GO(timeGetTime, vFv)
GO(DefDriverProc, vFv)
GO(OpenDriverA,iSppp)
GO(OpenDriver, vFv)
GO(timeGetDevCaps, vFv)
GO(timeBeginPeriod, vFv)
GO(joyGetNumDevs, vFv)
GO(GetModuleBaseNameA, vFv)
GO(LoadIconA, vFv)
GO(LoadStringA, vFv)
GO(wsprintfA,iFpv, vFv)
GO(GetDC, vFv)
GO(GetDesktopWindow, vFv)
GO(ReleaseDC, vFv)
GO(IsRectEmpty, vFv)
GO(LoadCursorA, vFv)
GO(SetCursor, vFv)
GO(GetCursorPos, vFv)
GO(SetCursorPos, vFv)
GO(ShowCursor, vFv)
GO(RegisterWindowMessageA, vFv)
GO(GetSystemMetrics, vFv)
GO(GetSysColor, vFv)
GO(GetSysColorBrush, vFv)
GO(GetWindowDC, vFv)
GO(DrawTextA, vFv)
GO(MessageBoxA, vFv)
GO(RegisterClassA, vFv)
GO(UnregisterClassA, vFv)
GO(GetWindowRect, vFv)
GO(MonitorFromWindow, vFv)
GO(MonitorFromRect, vFv)
GO(MonitorFromPoint, vFv)
GO(EnumDisplayMonitors, vFv)
GO(GetMonitorInfoA, vFv)
GO(EnumDisplayDevicesA, vFv)
GO(IsWindowVisible, vFv)
GO(GetActiveWindow, vFv)
GO(GetClassNameA, vFv)
GO(GetClassInfoA, vFv)
GO(GetWindowLongA, vFv)
GO(EnumWindows, vFv)
GO(GetWindowThreadProcessId, vFv)
GO(CreateWindowExA, vFv)
GO(MessageBeep, vFv)
GO(DialogBoxParamA, vFv)
GO(RegisterClipboardFormatA, vFv)
GO(CharNextA, vFv)
GO(EnumDisplaySettingsA, vFv)
GO(SystemParametersInfoA, vFv)
GO(PeekMessageA, vFv)
GO(RegCloseKey, vFv)
GO(RegCreateKeyA, vFv)
GO(RegCreateKeyExA, vFv)
GO(RegEnumKeyExA, vFv)
GO(RegEnumValueA, vFv)
GO(RegOpenKeyA, vFv)
GO(RegOpenKeyExA, vFv)
GO(RegQueryValueExA, vFv)
GO(RegSetValueExA, vFv)
GO(RegQueryInfoKeyA, vFv)
GO(CreateCompatibleDC, vFv)
GO(CreateFontA, vFv)
GO(DeleteDC, vFv)
GO(DeleteObject, vFv)
GO(GetDeviceCaps, vFv)
GO(GetSystemPaletteEntries, vFv)
GO(CreatePalette,iFv, vFv)
GO(GetObjectA, vFv)
GO(GetCharABCWidthsA, vFv)
GO(SetTextAlign, vFv)
GO(GetTextMetricsA, vFv)
GO(CreateDIBSection, vFv)
GO(SelectObject, vFv)
GO(CreateRectRgn, vFv)
GO(GetFileVersionInfoSizeA, pSp)
GO(CoCreateFreeThreadedMarshaler, vFv)
GO(CoCreateInstance, vFv)
GO(CoInitialize, vFv)
GO(CoInitializeEx, vFv)
GO(CoUninitialize,vFv)
GO(CoTaskMemAlloc, vFv)
GO(CoTaskMemFree, vFv)
GO(StringFromGUID2, vFv)
GO(PropVariantClear, vFv)
GO(memcpy,pFpv)
GO(wcscpy,pFpv)
GO(StringFromGUID2, vFv)
GO(InitCommonControls, vFv)
GO(htonl, uFu)
GO(ntohl, uFu)
GO(memcpy,pFpv) // just test
GO(MoCopyMediaType, vFv)
GO(MoCreateMediaType, vFv)
GO(MoDeleteMediaType, vFv)
GO(MoDuplicateMediaType, vFv)
GO(MoFreeMediaType, vFv)
GO(MoInitMediaType, vFv)
GO(SysFreeString, vFv)
GO(VariantInit, vFv)
GO(SysStringByteLen,iFv)
GO(malloc,pFi) // just test
GO(free,vFp) // just test
GO(fprintf,iFpv) // just test
GO(_ftol,IFv)
GO(_initterm,iFpp)
GO(__dllonexit,pFv)
GO(strncpy,pFp)
GO(_CIpow,dFv)
GO(calloc,vFi)
GO(memmove,pFp)
GO(ldexp, dFdi)
GO(frexp, dFdp)
GO(DirectDrawCreate,iFv)
GO(GetOpenFileNameA, uSp)
GO(PathFindExtensionA, pSp)
GO(PathFindFileNameA, pSp)
GO(_CIpow,dFv)
GO(_CIsin,dFv)
GO(_CIcos,dFv)
GO(_CIsqrt,dFv)
GO(memcpy,pFpv)
GO(memset,pFpv)
GO(sprintf,iFpv)
GO(strncpy,pFpv)
GO(fopen,pFpv)
GO(malloc,pFi)
GO(free,vFp)
GO(_initterm_e,iFpv)
GO(_initterm,iFpv)
GO(_decode_pointer,iFv)
GO(_splitpath,vFc)
GO(_mbsupr,cFc)
GO(_time64,IFv)
GO(memcpy,pFpv)
GO(memset,pFpv)
GO(_initterm_e,iFpv)
GO(_initterm,iFpv)
GO(SDL_GetRelativeMouseState,vFi)
GO(SDL_NumJoysticks,iFv)
GO(SDL_GameControllerGetAxis,wFpi)
GO(wglGetProcAddress,pSp)

GO(pfnPrecacheModel,iFp)
GO(pfnPrecacheSound,iFp)
GO(pfnSetModel,vFpp)
GO(pfnModelIndex,iFp)
GO(pfnModelFrames,iFi)
GO(pfnSetSize,vFppp)
GO(pfnChangeLevel,vFpp)
GO(pfnGetSpawnParms,vFp)
GO(pfnSaveSpawnParms,vFp)
GO(pfnVecToYaw,fFp)
GO(pfnVecToAngles,vFpp)
GO(pfnMoveToOrigin,vFppfi)
GO(pfnChangeYaw,vFp)
GO(pfnChangePitch,vFp)
GO(pfnFindEntityByString,pFppp)
GO(pfnGetEntityIllum,iFp)
GO(pfnFindEntityInSphere,pFppf)
GO(pfnFindClientInPVS,pFp)
GO(pfnEntitiesInPVS,pFp)
GO(pfnMakeVectors,vFp)
GO(pfnAngleVectors,vFpppp)
GO(pfnCreateEntity,pFv)
GO(pfnRemoveEntity,vFp)
GO(pfnCreateNamedEntity,pFi)
GO(pfnMakeStatic,vFp)
GO(pfnEntIsOnFloor,iFp)
GO(pfnDropToFloor,iFp)
GO(pfnWalkMove,iFpffi)
GO(pfnSetOrigin,vFpp)
GO(pfnEmitSound,vFpippfii)
GO(pfnEmitAmbientSound,vFpppffii)
GO(pfnTraceLine,vFppipp)
GO(pfnTraceToss,vFppp)
GO(pfnTraceMonsterHull,iFpppipp)
GO(pfnTraceHull,vFppiipp)
GO(pfnTraceModel,vFppipp)
GO(pfnTraceTexture,pFppp)
GO(pfnTraceSphere,vFppifpp)
GO(pfnGetAimVector,vFpfp)
GO(pfnServerCommand,vFp)
GO(pfnServerExecute,vFv)
GO(pfnClientCommand,vFppV)
GO(pfnParticleEffect,vFppff)
GO(pfnLightStyle,vFip)
GO(pfnDecalIndex,iFp)
GO(pfnPointContents,iFp)
GO(pfnMessageBegin,vFiipp)
GO(pfnMessageEnd,vFv)
GO(pfnWriteByte,vFi)
GO(pfnWriteChar,vFi)
GO(pfnWriteShort,vFi)
GO(pfnWriteLong,vFi)
GO(pfnWriteAngle,vFf)
GO(pfnWriteCoord,vFf)
GO(pfnWriteString,vFp)
GO(pfnWriteEntity,vFi)
GO(pfnCVarRegister,vFp)
GO(pfnCVarGetFloat,fFp)
GO(pfnCVarGetString,pFp)
GO(pfnCVarSetFloat,vFpf)
GO(pfnCVarSetString,vFpp)
GO(pfnAlertMessage,vFupV)
GO(pfnEngineFprintf,vFppV)
GO(pfnPvAllocEntPrivateData,pFpi)
GO(pfnPvEntPrivateData,pFp)
GO(pfnFreeEntPrivateData,vFp)
GO(pfnSzFromIndex,pFi)
GO(pfnAllocString,iFp)
GO(pfnGetVarsOfEnt,pFp)
GO(pfnPEntityOfEntOffset,pFi)
GO(pfnEntOffsetOfPEntity,iFp)
GO(pfnIndexOfEdict,iFp)
GO(pfnPEntityOfEntIndex,pFi)
GO(pfnFindEntityByVars,pFp)
GO(pfnGetModelPtr,pFp)
GO(pfnRegUserMsg,iFpi)
GO(pfnAnimationAutomove,vFpf)
GO(pfnGetBonePosition,vFpipp)
GO(pfnFunctionFromName,uFp)
GO(pfnNameForFunction,pFu)
GO(pfnClientPrintf,vFpup)
GO(pfnServerPrint,vFp)
GO(pfnCmd_Args,pFv)
GO(pfnCmd_Argv,pFi)
GO(pfnCmd_Argc,iFv)
GO(pfnGetAttachment,vFpipp)
GO(pfnCRC32_Init,vFp)
GO(pfnCRC32_ProcessBuffer,vFppi)
GO(pfnCRC32_ProcessByte,vFpc)
GO(pfnCRC32_Final,uFu)
GO(pfnRandomLong,iFii)
GO(pfnRandomFloat,fFff)
GO(pfnSetView,vFpp)
GO(pfnTime,fFv)
GO(pfnCrosshairAngle,vFpff)
GO(pfnLoadFileForMe,pFpp)
GO(pfnFreeFile,vFp)
GO(pfnEndSection,vFp)
GO(pfnCompareFileTime,iFppp)
GO(pfnGetGameDir,vFp)
GO(pfnCvar_RegisterVariable,vFp)
GO(pfnFadeClientVolume,vFpiiii)
GO(pfnSetClientMaxspeed,vFpf)
GO(pfnCreateFakeClient,pFp)
GO(pfnRunPlayerMove,vFppfffwcc)
GO(pfnNumberOfEntities,iFv)
GO(pfnGetInfoKeyBuffer,pFp)
GO(pfnInfoKeyValue,pFpp)
GO(pfnSetKeyValue,vFppp)
GO(pfnSetClientKeyValue,vFippp)
GO(pfnIsMapValid,iFp)
GO(pfnStaticDecal,vFpiii)
GO(pfnPrecacheGeneric,iFp)
GO(pfnGetPlayerUserId,iFp)
GO(pfnBuildSoundMsg,vFpippfiiiipp)
GO(pfnIsDedicatedServer,iFv)
GO(pfnCVarGetPointer,pFp)
GO(pfnGetPlayerWONId,uFp)
GO(pfnInfo_RemoveKey,vFpp)
GO(pfnGetPhysicsKeyValue,pFpp)
GO(pfnSetPhysicsKeyValue,vFppp)
GO(pfnGetPhysicsInfoString,pFp)
GO(pfnPrecacheEvent,wFip)
GO(pfnPlaybackEvent,vFipwfppffiiii)
GO(pfnSetFatPVS,pFp)
GO(pfnSetFatPAS,pFp)
GO(pfnCheckVisibility,iFpp)
GO(pfnDeltaSetField,vFpp)
GO(pfnDeltaUnsetField,vFpp)
GO(pfnDeltaAddEncoder,vFpp)
GO(pfnGetCurrentPlayer,iFv)
GO(pfnCanSkipPlayer,iFp)
GO(pfnDeltaFindField,iFpp)
GO(pfnDeltaSetFieldByIndex,vFpi)
GO(pfnDeltaUnsetFieldByIndex,vFpi)
GO(pfnSetGroupMask,vFii)
GO(pfnCreateInstancedBaseline,iFip)
GO(pfnCvar_DirectSet,vFpp)
GO(pfnForceUnmodified,vFuppp)
GO(pfnGetPlayerStats,vFppp)
GO(pfnAddServerCommand,vFpp)
GO(pfnVoice_GetClientListening,iFii)
GO(pfnVoice_SetClientListening,iFiii)
GO(pfnGetPlayerAuthId,pFp)
GO(pfnSequenceGet,pFpp)
GO(pfnSequencePickSentence,pFpip)
GO(pfnGetFileSize,iFp)
GO(pfnGetApproxWavePlayLen,uFp)
GO(pfnIsCareerMatch,iFv)
GO(pfnGetLocalizedStringLength,iFp)
GO(pfnRegisterTutorMessageShown,vFi)
GO(pfnGetTimesTutorMessageShown,iFi)
GO(pfnProcessTutorMessageDecayBuffer,vFpi)
GO(pfnConstructTutorMessageDecayBuffer,vFpi)
GO(pfnResetTutorMessageDecayData,vFv)
GO(pfnQueryClientCvarValue,vFpp)
GO(pfnQueryClientCvarValue2,vFppi)
GO(pfnCheckParm,iFpp)
